-- ============================================================
-- Agentic Procurement System — Supabase Database Schema
-- Execute this SQL in the Supabase SQL Editor.
-- ============================================================

-- 1. Suppliers
CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id   TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    reliability_score   INT NOT NULL DEFAULT 0,
    avg_delivery_days   INT NOT NULL DEFAULT 0,
    payment_terms TEXT NOT NULL DEFAULT 'Net-30'
);

-- 2. Items (inventory / catalog)
CREATE TABLE IF NOT EXISTS items (
    item_id       TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    category      TEXT NOT NULL DEFAULT 'General',
    current_stock INT NOT NULL DEFAULT 0
);

-- 3. Purchase History
CREATE TABLE IF NOT EXISTS purchase_history (
    po_id           TEXT PRIMARY KEY,
    item_id         TEXT NOT NULL REFERENCES items(item_id),
    supplier_id     TEXT NOT NULL REFERENCES suppliers(supplier_id),
    unit_price_sen  INT  NOT NULL,
    purchase_date   DATE NOT NULL DEFAULT CURRENT_DATE
);

-- 4. Purchase Orders (generated by the system)
CREATE TABLE IF NOT EXISTS purchase_orders (
    new_po_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    supplier_id      TEXT NOT NULL REFERENCES suppliers(supplier_id),
    total_amount_sen INT  NOT NULL,
    status           TEXT NOT NULL DEFAULT 'PENDING',
    approved_by      TEXT
);

-- 5. Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    log_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp     TIMESTAMPTZ NOT NULL DEFAULT now(),
    action_type   TEXT NOT NULL,
    agent_name    TEXT NOT NULL,
    decision_json JSONB
);

-- ============================================================
-- Seed data (optional — gives the agents something to work with)
-- ============================================================

INSERT INTO suppliers (supplier_id, name, contact_email, reliability_score, avg_delivery_days, payment_terms) VALUES
    ('SUP-A', 'Alpha Tech Solutions',  'orders@alphatech.com',  85, 14, 'Net-30'),
    ('SUP-B', 'Global IT Supplies',    'sales@globalit.com',    98,  7, 'Net-60'),
    ('SUP-C', 'BudgetHW Direct',       'support@budgethw.com',  72, 21, 'Net-15')
ON CONFLICT (supplier_id) DO NOTHING;

INSERT INTO items (item_id, name, category, current_stock) VALUES
    ('IT-XPS-15',  'Dell XPS 15 Laptop',       'IT Equipment', 4),
    ('IT-MBP-14',  'MacBook Pro 14"',           'IT Equipment', 12),
    ('OF-CHAIR-E', 'Ergonomic Office Chair',    'Furniture',    30)
ON CONFLICT (item_id) DO NOTHING;

INSERT INTO purchase_history (po_id, item_id, supplier_id, unit_price_sen, purchase_date) VALUES
    ('PO-2025-001', 'IT-XPS-15',  'SUP-B', 365000, '2025-08-20'),
    ('PO-2025-002', 'IT-MBP-14',  'SUP-A', 520000, '2025-07-10'),
    ('PO-2025-003', 'OF-CHAIR-E', 'SUP-C',  45000, '2025-09-01')
ON CONFLICT (po_id) DO NOTHING;

-- ============================================================
-- Schema v2 migrations
-- ============================================================

-- Add delivery_days to purchase_history (missing from v1)
ALTER TABLE purchase_history ADD COLUMN IF NOT EXISTS delivery_days INT NOT NULL DEFAULT 0;

-- Update seed data with delivery_days
UPDATE purchase_history SET delivery_days = 7  WHERE po_id = 'PO-2025-001';
UPDATE purchase_history SET delivery_days = 12 WHERE po_id = 'PO-2025-002';
UPDATE purchase_history SET delivery_days = 21 WHERE po_id = 'PO-2025-003';

-- Add item_id, quantity, pdf_url to purchase_orders
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS item_id  TEXT REFERENCES items(item_id);
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS quantity  INT;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS pdf_url  TEXT;

-- Evaluations: persists full pipeline state per chat session
CREATE TABLE IF NOT EXISTS evaluations (
    session_id      TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'PLANNING',
    plan_json       JSONB,
    current_step    TEXT,
    state_json      JSONB,
    report_markdown TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);