from __future__ import annotations


async def generate_report(
    evaluated_suppliers: list[dict],
    item_name: str,
    requested_qty: int,
    stock_sufficient: bool | None = None,
    current_stock: int | None = None,
) -> dict:
    """Build the markdown supplier-comparison report from evaluated supplier data (no LLM call).

    evaluated_suppliers may be empty — the supervisor can route straight here when stock was
    already sufficient, skipping Sourcing/Evaluation entirely.
    """
    recommended = next((s for s in evaluated_suppliers if s.get("is_recommended")), None)

    stock_notice = ""
    if stock_sufficient is not None:
        if stock_sufficient:
            stock_notice = (
                f"\n> **Stock notice:** {current_stock} units in stock — sufficient.\n"
            )
        else:
            stock_notice = (
                f"\n> ⚠️ **Stock notice:** Only {current_stock} units in stock — "
                f"{requested_qty} requested. Procurement required.\n"
            )

    comparison_section = ""
    if evaluated_suppliers:
        table_rows = "\n".join(
            f"| {s['supplier_name']} | RM {s['unit_price_sen'] / 100:,.2f} | "
            f"{s['quoted_delivery_days']} days | {s.get('payment_terms', 'N/A')} | "
            f"{s['total_score']:.1f} | {'✅ Recommended' if s['is_recommended'] else ''} |"
            for s in sorted(evaluated_suppliers, key=lambda x: x["total_score"], reverse=True)
        )
        comparison_section = (
            "### Supplier Comparison\n\n"
            "| Supplier | Unit Price | Delivery | Payment Terms | Score | Recommendation |\n"
            "|----------|-----------|----------|---------------|-------|----------------|\n"
            f"{table_rows}\n\n---\n\n"
        )

    risk_section = ""
    for s in evaluated_suppliers:
        if s.get("risk_flags"):
            risk_section += f"\n**{s['supplier_name']} risks:**\n"
            for flag in s["risk_flags"]:
                risk_section += f"- ⚠️ {flag}\n"

    if recommended:
        recommendation_section = (
            f"### Recommendation\n\n"
            f"**{recommended['supplier_name']}** is recommended with a total score of "
            f"**{recommended['total_score']:.1f}/100**.\n\n"
            f"Estimated unit price: RM {recommended['unit_price_sen'] / 100:,.2f} | "
            f"Delivery: {recommended['quoted_delivery_days']} days\n\n"
            f"{recommended.get('reasoning', '')}\n"
        )
    else:
        recommendation_section = (
            "### Recommendation\n\nNo supplier evaluation was needed for this request.\n"
        )

    # Approval language only when there's actually something to approve — a stock check or
    # satisfied top-up ends here, with no PO step after it.
    title = "Procurement Evaluation Report" if evaluated_suppliers else "Inventory Report"
    footer = (
        "*Evaluation performed by AI Procurement Operations System. "
        "Approve below to generate a PO.*"
        if evaluated_suppliers
        else "*Report generated by AI Procurement Operations System.*"
    )

    # qty 0 = a pure "how much do we have?" stock check — a "0 units requested" line reads
    # like a bug, so drop it.
    qty_line = f"\n**Requested Quantity:** {requested_qty} units" if requested_qty else ""

    markdown = f"""## {title}

**Item:** {item_name}{qty_line}
{stock_notice}
---

{comparison_section}{recommendation_section}
{risk_section}
---

{footer}
"""
    return {"report_markdown": markdown.strip()}
